### PR TITLE
spark agent #372 fix configuration stack lookup

### LINKED ISSUE #372: Exceptions are swallowed in AgentBOM.postProcessingFilter
```scala
    override lazy val postProcessingFilter: Option[PostProcessingFilter] = {
      tryObtainAll[PostProcessingFilter](ConfProperty.RootPostProcessingFilter)
        .map(new CompositePostProcessingFilter(_))
        .toOption // <-- HERE
    }
```

### PR DESCRIPTION
**Pull request by cerveada**
- throw all exceptions for dispacther/filters configured
- use default only if other dispacther/filters are not configured
- use passwordReplacingFilter by default
- fix SparApp filter config

fixes #372

### CODE REVIEW

File: core/src/main/scala/za/co/absa/spline/agent/AgentBOM.scala [hunk 1]
```diff
@@ -63,15 +61,36 @@ object AgentBOM {
     }
 
     override lazy val postProcessingFilter: Option[PostProcessingFilter] = {
-      tryObtainAll[PostProcessingFilter](ConfProperty.RootPostProcessingFilter)
-        .map(new CompositePostProcessingFilter(_))
-        .toOption
+      val nonDefaultRefs = configs.flatMap(_.getOptionalObject[AnyRef](ConfProperty.RootPostProcessingFilter))
+      val refs =
+        if(nonDefaultRefs.nonEmpty) {
```
Comment (wajda) [inline core/src/main/scala/za/co/absa/spline/agent/AgentBOM.scala]: nit: missing white space

File: core/src/main/scala/za/co/absa/spline/agent/AgentBOM.scala [hunk 2]
```diff
@@ -63,15 +61,36 @@ object AgentBOM {
...
+      }
     }
 
     override lazy val lineageDispatcher: LineageDispatcher = {
-      tryObtainAll[LineageDispatcher](ConfProperty.RootLineageDispatcher)
-        .map(new CompositeLineageDispatcher(_, failOnErrors = false))
-        .get
+      val nonDefaultRefs = configs.flatMap(_.getOptionalObject[AnyRef](ConfProperty.RootLineageDispatcher))
+      val refs=
+        if(nonDefaultRefs.nonEmpty) {
```
Comment (wajda) [inline core/src/main/scala/za/co/absa/spline/agent/AgentBOM.scala]: nit: missing white spaces

File: core/src/main/scala/za/co/absa/spline/agent/AgentBOM.scala [hunk 3]
```diff
@@ -63,15 +61,36 @@ object AgentBOM {
...
+            .getOrElse(Seq.empty)
+        }
+
+      val filters = refs.map(obtain[PostProcessingFilter](ConfProperty.RootPostProcessingFilter, _))
+
+      if (filters.nonEmpty) {
+        Some(new CompositePostProcessingFilter(filters))
+      } else {
+        None
+      }
```
Comment (wajda) [inline core/src/main/scala/za/co/absa/spline/agent/AgentBOM.scala]:
```suggestion
      filters.asOption.map({
        case Seq(filter) => filter
        case _ => new CompositePostProcessingFilter(filters)
      })
```

The method `TraversableWrapper.asOption` replaces the `if  (xs.nonEmpty)`. Also we probably do not need to wrap a single filter with a composite.

**Review by wajda — APPROVED** [review]
