### PR TITLE
spark agent #289 improve write extraction fail logs

### LINKED ISSUE #289: Redesing the behaviour when Write command is not recognized
- Currently, the message that appears in logs differs depending on spline mode, which is confusing.
- When there is an error, it could be a good idea to try to use structure dumper (but catch any errors form there)
- generaly make the logs the same in the same sittuation (only additional details hould be added / missing)

This happens in #286

### PR DESCRIPTION
**Pull request by cerveada**
Fixes #289

### CODE REVIEW

File: core/src/main/scala/za/co/absa/spline/harvester/logging/ObjectStructureLogging.scala [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+    if (log.isErrorEnabled) logObjectStructure(obj, log.error, log.error)
+
+  private def logObjectStructure(
+    obj: AnyRef,
+    logMethod: String => Unit,
+    logMethodThrowable: (String, Throwable) => Unit
+  ): Unit =
+    Try(ObjectStructureDumper.dump(obj)) match {
+      case Success(s) => logMethod(s)
+      case Failure(e) if NonFatal(e) => logMethodThrowable(s"Attempt to dump structure of ${obj.getClass} failed", e)
```
Comment (wajda) [inline core/src/main/scala/za/co/absa/spline/harvester/logging/ObjectStructureLogging.scala]: When using `Try` checking for `NonFatal` is redundant. `Try` only catches non-fatal errors by definition.

File: core/src/main/scala/za/co/absa/spline/harvester/logging/ObjectStructureLogging.scala [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+import org.apache.spark.internal.Logging
+
+import scala.util.control.NonFatal
+import scala.util.{Failure, Success, Try}
+
+trait ObjectStructureLogging {
+  self: Logging =>
+
+  protected def logTraceObjectStructure(obj: => AnyRef): Unit =
+    if (log.isTraceEnabled) logObjectStructure(obj, log.trace, log.trace)
```
Comment (wajda) [inline core/src/main/scala/za/co/absa/spline/harvester/logging/ObjectStructureLogging.scala:28]: Though `log` has a type of `slf4j.Logger` the trait itself is combined with `spark.Logging` that has `logXXX()` methods doing the same thing. So we can use them directly instead of the `log` (that is one level more distant dependency).
```suggestion
    logObjectStructure(obj, logTrace, logTrace)
```

File: core/src/main/scala/za/co/absa/spline/harvester/logging/ObjectStructureLogging.scala [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+
+  protected def logWarningObjectStructure(obj: => AnyRef): Unit =
+    if (log.isWarnEnabled) logObjectStructure(obj, log.warn, log.warn)
+
+  protected def logErrorObjectStructure(obj: => AnyRef): Unit =
+    if (log.isErrorEnabled) logObjectStructure(obj, log.error, log.error)
+
+  private def logObjectStructure(
+    obj: AnyRef,
+    logMethod: String => Unit,
```
Comment (wajda) [inline core/src/main/scala/za/co/absa/spline/harvester/logging/ObjectStructureLogging.scala]: naming: it might sound picky but sill - `logMethod` is not a method but a function. It confused me for a second when I read it like "log the method ...". I'd name it `logFn`

**Review by wajda — APPROVED** [review]
