### PR TITLE
#536 - tests fails on windows

### LINKED ISSUE #536: Tests fail on Windows
Having tried to run `tests` on Windows (Win 11 x64) with docker-desktop alternative running, I am failing to test-run the project.

I have run `mvn test > out.txt`, attaching a log
[out.zip](https://github.com/AbsaOSS/spline-spark-agent/files/10075978/out.zip)

@cerveada @miroslavpojer

### PR DESCRIPTION
**Pull request by miroslavpojer**
- fixed 12 failing tests related to windows-like paths comparison

Closes #536

### CODE REVIEW

**Comment by wajda** [comment]
Now tests are failing on Linux
```
org.scalatest.exceptions.TestFailedException: URI file:/tmp/SparkFixture3286681055411943221UnitTest/sourcetable was not the same as expected file://tmp/SparkFixture3286681055411943221UnitTest/sourcetable
```

**Comment by miroslavpojer** [comment]
> Now tests are failing on Linux
> 
> ```
> org.scalatest.exceptions.TestFailedException: URI file:/tmp/SparkFixture3286681055411943221UnitTest/sourcetable was not the same as expected file://tmp/SparkFixture3286681055411943221UnitTest/sourcetable
> ```

Solved in following commits. Build server has been used to run & show these problems as I am running on windows machine.

File: integration-tests/src/test/scala/za/co/absa/spline/ExcelSpec.scala [hunk 1]
```diff
@@ -25,12 +25,15 @@ import za.co.absa.commons.io.{TempDirectory, TempFile}
...
 
+import java.io.File
+
 class ExcelSpec extends AsyncFlatSpec
   with Matchers
   with SparkFixture
   with SplineFixture {
 
   private val filePath = TempFile("file1", ".xlsx", false).deleteOnExit().path.toAbsolutePath.toString
+  private val fileUri = new File(filePath).toURI.toString
```
Comment (wajda) [inline integration-tests/src/test/scala/za/co/absa/spline/ExcelSpec.scala]: minor:
unnecessary `toString` call. The name `fileUri` suggests it is of the `URI` type, while in fact is `String`. If would be OK in other situations where it's passed to the expressions where a string is expected. But in this particular context (and the other similar ones in this PR) the given variable is only used in string interpolation, where `Any` is expected and `toString` is called implicitly. So it would be more natural for `fileUri` variable to be of the `URI` type.

File: integration-tests/src/test/scala/za/co/absa/spline/ExcelSpec.scala [hunk 2]
```diff
@@ -63,7 +66,7 @@ class ExcelSpec extends AsyncFlatSpec
         } yield {
           plan1.operations.write.append shouldBe false
           plan1.operations.write.extra.get("destinationType") shouldBe Some("excel")
-          plan1.operations.write.outputSource shouldBe s"file:$filePath"
+          plan1.operations.write.outputSource shouldBe s"$fileUri"
```
Comment (wajda) [inline integration-tests/src/test/scala/za/co/absa/spline/ExcelSpec.scala]: Redundant string interpolation:
```suggestion
          plan1.operations.write.outputSource shouldBe fileUri
```

**Review by wajda — COMMENTED** [review]
LGTM excepts for redundant `toString` and `s"$xxx"` as commented below.

File: integration-tests/src/test/scala/za/co/absa/spline/ExcelSpec.scala (hunk 1 above)
Comment (cerveada) [reply integration-tests/src/test/scala/za/co/absa/spline/ExcelSpec.scala]: maybe `toURI` method should be added to `TempFile` and `TempDirectory` so you can call 
```scala
private val fileUri = TempFile("file1", ".xlsx", false).deleteOnExit().toURI
```

File: integration-tests/src/test/scala/za/co/absa/spline/SQLCommandsSpec.scala [hunk 3]
```diff
@@ -58,9 +60,9 @@ class SQLCommandsSpec extends AsyncFlatSpec
                   | WHERE id > 1""".stripMargin))
 
           } yield {
-            plan1.operations.write.outputSource should equalToUri(s"file:$warehouseDir/sourcetable")
+            plan1.operations.write.outputSource should equalToUri(s"${warehouseUri.toString}/sourcetable")
             plan2.operations.reads.get.head.inputSources.head should equalToUri(plan1.operations.write.outputSource)
-            plan2.operations.write.outputSource should equalToUri(s"file:$warehouseDir/targettable")
+            plan2.operations.write.outputSource should equalToUri(s"${warehouseUri.toString}/targettable")
```
Comment (cerveada) [inline integration-tests/src/test/scala/za/co/absa/spline/SQLCommandsSpec.scala]: You don't need `toString` here it's called automatically when using `s"$warehouseUri"`

File: integration-tests/src/test/scala/za/co/absa/spline/harvester/LineageHarvesterSpec.scala [hunk 4]
```diff
@@ -52,7 +53,7 @@ class LineageHarvesterSpec extends AsyncFlatSpec
       withLineageTracking { captor =>
         import spark.implicits._
 
-        val testDest = tmpDest
+        val testDest = tmpDest.asString
```
Comment (cerveada) [inline integration-tests/src/test/scala/za/co/absa/spline/harvester/LineageHarvesterSpec.scala]: In this case the code would be clearer using `tmpDest()` to make it known that method is called. I thought it was variable for some time.

Also it is recomended in scala style guide
https://docs.scala-lang.org/style/method-invocation.html#arity-0

Comment (cerveada) [reply integration-tests/src/test/scala/za/co/absa/spline/harvester/LineageHarvesterSpec.scala]: or you could just delete the method and use the code directly it's really short and it would make it obvious what is happening.

File: integration-tests/src/test/scala/za/co/absa/spline/ExcelSpec.scala (hunk 2 above)
Comment (miroslavpojer) [reply integration-tests/src/test/scala/za/co/absa/spline/ExcelSpec.scala]: Agreed. Solved in following series of commit.

File: integration-tests/src/test/scala/za/co/absa/spline/SQLCommandsSpec.scala (hunk 3 above)
Comment (miroslavpojer) [reply integration-tests/src/test/scala/za/co/absa/spline/SQLCommandsSpec.scala]: Fixed in commit e54f5ef9a17cf0c9ad82fbc7081d401b31a933b3.

File: integration-tests/src/test/scala/za/co/absa/spline/harvester/LineageHarvesterSpec.scala (hunk 4 above)
Comment (miroslavpojer) [reply integration-tests/src/test/scala/za/co/absa/spline/harvester/LineageHarvesterSpec.scala]: Fixed in commit 5d0f9ae49f2b674bea77d05b7807d51df7eacc06.

File: integration-tests/src/main/scala/za/co/absa/spline/test/fixture/SparkFixture.scala [hunk 5]
```diff
@@ -22,21 +22,27 @@ import org.scalatest.{Assertion, AsyncTestSuite, BeforeAndAfterEach}
...
+  val metastoreDir: String = TempDirectory("Metastore", "debug", pathOnly = true).deleteOnExit().asString
+  val metastoreConnectURL = s"jdbc:derby:$metastoreDir/metastore_db;create=true"
 
   protected val sessionBuilder: SparkSession.Builder = {
     SparkSession.builder
       .master("local")
       .config("spark.driver.host","localhost")
       .config("spark.sql.warehouse.dir", warehouseDir)
       .config("spark.ui.enabled", "false")
+      .config("javax.jdo.option.ConnectionURL", metastoreConnectURL)
```
Comment (cerveada) [inline integration-tests/src/main/scala/za/co/absa/spline/test/fixture/SparkFixture.scala:45]: What is this config needed for?

**Review by cerveada — APPROVED** [review]

**Review by wajda — APPROVED** [review]
lgtm

File: integration-tests/src/main/scala/za/co/absa/spline/test/fixture/SparkFixture.scala (hunk 5 above)
Comment (miroslavpojer) [reply integration-tests/src/main/scala/za/co/absa/spline/test/fixture/SparkFixture.scala:45]: It is used to define custom paths to metastore_db. It solves an issue found on windows where default location was still hold by process when trying to apply clean logic.
