### PR TITLE
spark agent #479 add support for delta lake 1.2+

### LINKED ISSUE #479: ViewAttributeAddingFilter causing java.util.NoSuchElementException: None.get
**Version：**

- JDK: 11.0.10
- Scala: 2.12.12
- Hadoop: 3.2.2
- Spark: 3.2.0-bin-hadoop3.2
- spline: release/0.7.7
- spline-ui: release/0.7.4
- spline-spark-agent: release/0.7.10
- Delta Lake: 1.2.0
- Elasticsearch: 7.13.4

**Description:**
App is reading from a delta lake table and then writing into ES

**Error Log:**
[delta2es.log](https://github.com/AbsaOSS/spline-spark-agent/files/9148867/delta2es.log)

**Error information:**

- Delta2ES
```
22/07/20 15:15:33 ERROR SplineQueryExecutionListener: Unexpected error occurred during lineage processing for application: Waterdrop #application_1658293063172_0007
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:529)
	at scala.None$.get(Option.scala:527)
	at za.co.absa.spline.harvester.postprocessing.ViewAttributeAddingFilter.toAttributeReferencesMap(ViewAttributeAddingFilter.scala:59)
	at za.co.absa.spline.harvester.postprocessing.ViewAttributeAddingFilter.$anonfun$addMissingAttributeLinks$1(ViewAttributeAddingFilter.scala:39)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at za.co.absa.spline.harvester.postprocessing.ViewAttributeAddingFilter.addMissingAttributeLinks(ViewAttributeAddingFilter.scala:39)
	at za.co.absa.spline.harvester.postprocessing.ViewAttributeAddingFilter.processExecutionPlan(ViewAttributeAddingFilter.scala:34)
	at za.co.absa.spline.harvester.postprocessing.PostProcessor.$anonfun$process$4(PostProcessor.scala:38)
	at za.co.absa.spline.harvester.postprocessing.PostProcessor.$anonfun$provideCtx$1(PostProcessor.scala:25)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
	at za.co.absa.spline.harvester.postprocessing.PostProcessor.process(PostProcessor.scala:38)
	at za.co.absa.spline.harvester.LineageHarvester.$anonfun$harvest$4(LineageHarvester.scala:110)
	at scala.Option.flatMap(Option.scala:271)
	at za.co.absa.spline.harvester.LineageHarvester.harvest(LineageHarvester.scala:64)
	at za.co.absa.spline.harvester.QueryExecutionEventHandler.onSuccess(QueryExecutionEventHandler.scala:42)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$2(SplineQueryExecutionListener.scala:40)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$2$adapted(SplineQueryExecutionListener.scala:40)
	at scala.Option.foreach(Option.scala:407)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$1(SplineQueryExecutionListener.scala:40)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.withErrorHandling(SplineQueryExecutionListener.scala:49)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.onSuccess(SplineQueryExecutionListener.scala:40)
	at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:158)
	at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:128)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
	at org.apache.spark.sql.util.ExecutionListenerBus.postToAll(QueryExecutionListener.scala:128)
	at org.apache.spark.sql.util.ExecutionListenerBus.onOtherEvent(QueryExecutionListener.scala:140)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:100)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1404)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
```

```Scala
  override def output(data: Dataset[Row], env: SparkEnvironment): Unit = {
    val index: String = StringTemplate.substitute(config.getString("index"), config.getString("index_time_format"))
    val columns: Seq[Column] = data.schema.map((structField: StructField) => {
      val fieldType: String = structField.dataType.getClass.getName
      if ("org.apache.spark.sql.types.DecimalType".equals(fieldType) || "org.apache.spark.sql.catalyst.types.DecimalType".equals(fieldType)) {
        data.col(structField.name).cast(DataTypes.StringType)
      } else {
        data.col(structField.name).cast(DataTypes.StringType)
      }
    })
    val resource: String = if (config.hasPath("index_type")) index + "/" + config.getString("index_type") else index
//    data.select(columns: _*).saveToEs(resource, esConfig)
    data
      .select(columns: _*)
      .write
      .format("es")
      .option("es.nodes", esConfig.get("es.nodes"))
      .option("es.port", esConfig.getOrElse("port","9200"))
      .save(s"$resource")
  }
```

### PR DESCRIPTION
**Pull request by cerveada**
fixes #479, #480

### CODE REVIEW

File: core/src/test/scala/za/co/absa/spline/harvester/conf/StandardSplineConfigurationStackSpec.scala [hunk 1]
```diff
@@ -16,13 +16,25 @@
...
+
+  implicit val spark: SparkSession = SparkSession.builder()
+    .master("local[*]")
+    .appName(s"Commons unit testing SchemaUtils")
+    .config("spark.ui.enabled", "false")
+    .config("spark.debug.maxToStringFields", 100)
+    .config("spark.driver.bindAddress", "127.0.0.1")
+    .config("spark.driver.host", "127.0.0.1")
+    .config("spark.sql.hive.convertMetastoreParquet", false)
+    .config("fs.defaultFS","file:/")
```
Comment (wajda) [inline core/src/test/scala/za/co/absa/spline/harvester/conf/StandardSplineConfigurationStackSpec.scala]: why are all those properties there? Can we remove those that aren't relevant for the test suite?

**Review by wajda — COMMENTED** [review]
LGMT excepts for the question about the spark session test config.

File: core/src/test/scala/za/co/absa/spline/harvester/conf/StandardSplineConfigurationStackSpec.scala (hunk 1 above)
Comment (cerveada) [reply core/src/test/scala/za/co/absa/spline/harvester/conf/StandardSplineConfigurationStackSpec.scala]: Those are copied from `SparkTestBase`. Since this test class is removed in `develop` branch I haven't spent much time on it.

I guess `spark.debug.maxToStringFields`, `spark.sql.hive.convertMetastoreParquet` and `fs.defaultFS` could be removed.

**Review by wajda — DISMISSED** [review]

**Review by wajda — APPROVED** [review]
